### ISSUE TITLE
Disable validation when fields are pristine

### ISSUE THREAD

**Issue by ilourt** [codecks-io/react-reform#1]
I implement a form with 2 text fields (username and password). The problem is that validations rules are applyed even when fields are pristine (the don't have been touched).

Is there a way to only validate fields when they are not pristine?

**Comment by danielberndt** [comment]
Hey there,

have a look at line 10 within the [bootstrap-theme](https://github.com/danielberndt/react-reform/blob/71188c4713b0f4704481037ac1ce9a3ca19c7e16/src/opt/theme-bootstrap.js#L10).

Here I've implemented this behaviour by only showing the error if `isTouched` or `hasFailedToSubmit` is true (the latter being `true` if the submit button has been pressed, which might happen without touching the fields first)

You might wanna exchange `isTouched` for `isDirty`, to get the `pristine` behaviour.

Does this work for you?

**Comment by danielberndt** [comment]
Any remaining issues here @pezioz? Will close this issue soon otherwise.

**Comment by ilourt** [comment]
@danielberndt sorry for the delay in my response. I didn't have time recently to check it.
I will check this until the end of next week.

**Comment by danielberndt** [comment]
No worries. Please note that in the meantime the API and thus the bootstrap-theme has changed a bit. I.e. instead of `hasFailedToSubmit` you now need to check for `status === "preSubmitFail"` to replicate the behaviour I described above.
