### ISSUE TITLE
Docs of v1

### ISSUE THREAD

**Issue by jorgecuesta** [codecks-io/react-reform#11]
Hi, v1 look greats! when you plan make a release of it or almost put some readme with use guidelines to can implement it more quickly than reading your code.
Best Regards,

**Comment by danielberndt** [comment]
Ah, nice! Someone diving into the dark and secret parts of this library :)

I'd say v1 is release ready (i.e. I'm using it in production already) and you can already get the release by calling `npm install react-reform@beta`.

But yeah, the documentation will be quite some tough work though and my pre-christmas schedule is fairly busy. So I'm planning on dealing with it between Christimas and New Year's. If you have any concrete questions by then I'm happy to help :)

**Comment by jorgecuesta** [comment]
Hi,

Don't worry i'm using it and work like a charm.

Just find docs to do it more quickly.

Jorge Cuesta
Software Engineer @ Okkralabs
Skype: phiroarg 
Mobil: +543794767536
Corrientes, Corrientes (3400) - Argentina

**Comment by danielberndt** [comment]
I've just released v1.0 and first version of the docs here: http://react-reform.codecks.io/

Please let me know whether you're missing anything!

**Comment by jorgecuesta** [comment]
Thanks @danielberndt I will check it any time I need some thing of Form. Happy new year!
