### ISSUE TITLE
Error in submit returned promise

### ISSUE THREAD

**Issue by ilourt** [codecks-io/react-reform#2]
There is a problem when returning a rejected promise in the handle submit mehtod.

1) In form.js line 83 it must be:

```
if (fields[errorField])
```

instead of 

```
if (_this.fields[errorField])
```

2) Even this is corrected then I receive the following error:

```
Uncaught (in promise) Error: Objects are not valid as a React child (found: object with keys {globalErrors}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Form`.
```

coming from form.js:87

**Comment by danielberndt** [comment]
yes, you're right. thanks for letting me know! I'll fix this issue and add a test case later today.

regarding 2): how are you trying to render the error? The error message suggests you're not rendering a string but an object with a `globalErrors` property.

**Comment by danielberndt** [comment]
published version 0.3.3 to fix this issue. Let me know whether you still have issues regarding 2)

**Comment by ilourt** [comment]
Thanks the first point is well corrected.

About the 2nd point, I still have the problem when I use the named template from the example.
The 'globalErrors' variable contains an array of string.

DO you know what am I doing wrong?

**Comment by danielberndt** [comment]
I guess you're running into this case [here](https://github.com/danielberndt/react-reform/blob/d9673eb2982466536b2012752c44ddeaabd36977/src/core/form.js#L140).

i.e. it might be that you're not returning a string from the server but an object.
This case is currently not covered by the example themes.
