### ISSUE TITLE
Keep values in fields after submit

### ISSUE THREAD

**Issue by Travisism** [codecks-io/react-reform#21]
Example use case: A search field that displays a table below it with the results from an API call. After typing in your search and hitting submit, connect to the server, grab the results, display them in the table below it. This should leave the search term inside the search field.

Currently, it seems the only way to leave the values in their fields after submitting the form is to return a promise and either let it hang, or reject it. Letting it hang is just plain dirty, and rejecting it is definitely not the proper use for promises.

I've read the docs and can't seem to find this anywhere. How would I handle the situation above?

**Comment by danielberndt** [comment]
Did you find the section about [controlled forms](http://react-reform.codecks.io/docs/form/)?

My suggestion would be to use a controlled form, i.e you manage the value of the form itself and so you can decide when to clear or keep the input's value. 

Would this work for your use case?

**Comment by Travisism** [comment]
Hello,

Yes I did try that, however I now see that I missed the part where you have to specify the model={...} in the `<Form>` tag! So it was still resetting each time on submit. After now having added that in, it is working exactly as I need.

Thanks for your help, and sorry for the silly question.
