### ISSUE TITLE
Bootstrap Question

### ISSUE THREAD

**Issue by th3fallen** [codecks-io/react-reform#22]
Not sure if this is the place to ask questions but here goes none the less. With boostrap you usually define a fieldset around your inputs. but for a hidden input for example i would not want that. do you have any way to detect that and conditionally render the fieldset in creating a template, the one size fits all render method for inputs is cutting it for me.

I hope im just missing something.

**Comment by danielberndt** [comment]
Yes, I think for now issues are a good place for questions :)

And yes, there's a way to this! This is where the `type` attribute of a wrapped input comes in handy!

Have a look at some code to get an idea:

```
renderField: (Field, {validations, name, directProps: {label = name, ...restDirectProps}, formStatus, wrapperProps: {type}}) => {
  // ...
  switch (type) {
    case "Checkbox":
      return (
        <div>
          <Label errors={errors.map(({message}) => message)}>
            <Field {...restDirectProps} disabled={formStatus === "pending"}/> {label}
          </Label>
        </div>
      );
    default:
      return (
        <div>
          <Label errors={errors.map(({message}) => message)}>{label}</Label>
          <Field {...restDirectProps} disabled={formStatus === "pending"}/>
        </div>
      );
  }
}
```

This sample treats `Checkbox`es differently than the other types. You could do something similar to your hidden input if you pass the corresponding type via `WrapInput`.

**Comment by th3fallen** [comment]
you're the man! thanks
