### ISSUE TITLE
form valid

### ISSUE THREAD

**Issue by lucidprogrammer** [codecks-io/react-reform#4]
Form submit happens when the fields are valid. Fair enough. Is there a simple way to get isValid on the form itself, so that I can possibly disable the button itself? Only way I see now is to loop through the validations object for each field, there could be some simpler way to do this?

**Comment by danielberndt** [comment]
yes, this use case makes a lot of sense. 

I'll introduce another parameter to the `<FormContainer>` that will allow you to check the for the result of the field validations (and possibly a generic `isValid` value which is only true if all fields are valid)

**Comment by lucidprogrammer** [comment]
Thanks daniel.

**Comment by danielberndt** [comment]
v0.5.3 was just released. It adds both, a `validations` list and the more generic `isValid` to the `formContainerOpts`

**Comment by lucidprogrammer** [comment]
it works perfect, great work @danielberndt
