### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by lucidprogrammer** [codecks-io/react-reform#5]
Have you got any radiobutton group already created which can be shared?

**Comment by danielberndt** [comment]
No I didn't have the use case in my project yet, but I think that something like https://github.com/chenglou/react-radio-group should be quite straight forward to wrap:

```
const RadioGroup = wrapInput("RadioGroup", require("react-radio-group"), {
  valueToProps: value => {selectedValue: value},
});
```

and then use it like 

```
<Form ...>
  <RadioGroup name="xxx">
   {Radio => (
      <div>
        <Radio value="apple" />Apple
        <Radio value="orange" />Orange
        <Radio value="watermelon" />Watermelon
      </div>
    )}
  </RadioGroup>
</Form
```

I haven't tested it, but something close to this should do the job!

**Comment by lucidprogrammer** [comment]
tks
